### PR TITLE
ANS domains integration.

### PR DESCRIPTION
**Pull request by crypt0miester**
#### Problem

Add ANS Protocol domain search and show owned domains

#### Summary of Changes
Added ANS (Alternative Name Service) Protocol domains to the Explorer
- search by domain
- show owned domains

ANS enables any project on Solana to have their own TLD ( .anything )

the **.poor**, **.bonk**, **.abc**, **.eth**( bridged ENS domains through Wormhole [.bridge](https://bridge.onsol.io/) ) domains are enabled in the protocol

the protocol currently powers around 40K domains

we have already a few projects lined up to create their own domains through ANS

original PR on the previous repo: [#29277](https://github.com/solana-labs/solana/pull/29277)
original issue on the previous repo: solana-labs/explorer#205

Fixes #

####  Previews 
[Screencast from 27-04-23 06:30:22.webm](https://user-images.githubusercontent.com/77497858/234778702-ca5079c8-3b99-4bc9-93ef-37e7614772bc.webm)

### CODE REVIEW

**Comment by ngundotra** [comment]
Hey @crypt0miester can you write up an explanation of ANS on forum.solana.com?

**Review by steveluscher — CHANGES_REQUESTED** [review]
Whatever happens here, this PR will need to be updated because Explorer has been migrated to new infra as of #237.

**Comment by tonivlad** [comment]
Hey @ngundotra @mcintyre94 

I think it's about time we revisit this, since the last time we spoke some updates happened on our end:

we've been integrated in:
**SolanaFm Explorer**  - [link](https://twitter.com/solanafm/status/1752327438984745260)
**Solflare Wallet**
**Helium Mobile Wallet**
**SonarWatch**
and a few other dapps

our domain partner list has grown to include
**Superteam** - .superteam
**MonkeDao** - .monke
**DeanslistDAO** - .ser
**Myro** - .myro
**Samo** - .samo
**Eyekon** - .eyekon
and we have a long pipeline of projects that we will launch with

I know all of them would like to see their domains in the Solana Explorer

and we launched the FIRST Tokenized Web2 Domains on Solana with Pandi (the Indonesian Web2 domain registry)
**.id domains**
 that work both as Web3 domains and as Web2 domains

@steveluscher related to your [comment](https://github.com/solana-labs/explorer/pull/236#pullrequestreview-1463213955), the code has been updated to be compatible with the new infra.

didn't add any new screenshots or video because the integration works the same as before:
users can **search for domains** and they can **see what an address owns** in the Domains tab

Let me know if there is anything else to do to get this going

Thank you

**Comment by ngundotra** [comment]
Closed by #368

**Pull request closed without merging**
