### PR TITLE
Add anchor details to instruction card on tx inspector

### PR DESCRIPTION
**Pull request by brittcyr**
When possible, use the anchor description card instead of the default instruction card on the tx simulation page. This is useful because 

Before:
Screen Shot 2024-05-19 at 1 01 28 PM

After:
Screen Shot 2024-05-19 at 1 01 47 PM

### CODE REVIEW

**Comment by brittcyr** [comment]
This reuses the AnchorDetails card to bring instruction display mostly into parity between simulation and actual tx

**Comment by brittcyr** [comment]
Fixes #287

**Comment by brittcyr** [comment]
@mcintyre94 are you the right person to review this?

**Comment by brittcyr** [comment]
@ngundotra anything else need to be done here?

**Comment by brittcyr** [comment]
@ngundotra anything else need to be done here?

**Comment by ngundotra** [comment]
@brittcyr Can you share some example txs for me to check?

**Comment by brittcyr** [comment]
Mango:
https://explorer.solana.com/tx/inspector?signatures=%255B%255D&message=AgEFCRs9oIYKLgvCL0jE6NPJcNK91pYWO260fYJcwfKrssMBSKw4Jx8oqxsS5JQ5vd9UhxCU5IMqVseo7Fe9GNNXmAARLXtRsizCsBmLuz5XxlatdGYbAf3cIO%252Fv2redwO548ahCTS0yu5ZFC9WbgBoYsqjYpBA2jBaVRU%252F8xUOqzUrGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAx2OF93g9ZwY4HW5jKnWtlyPok7VBtIGxevjwYDwI3f1sXx8hqbnOfrxdRgYNj6U%252BQi%252FNwBM5tP7zxl73S9R8cnpF790xBuhB8qzeCi8CgG%252BhgNtFM%252FFwCEvgNQ7k1lS8DBkZv5SEXMv%252Fsrbpyw5vnvIzlu8X3EmssQ5s6QAAAAKniOeM8HNrJQualz8ir6fopKgIS9LznmB%252Bq%252BDvmdglOAggABQJAQg8ABQYGAQMHBAKhAZHMC9Guhk8%252BAcD3509w6CJfaPPr8MaPrubzIS6rA0AhgdwhdwHUfLHXAc3MzD0B%252BgAAAAEAAAHNzMw9AW8SgzoBZmZmPwHNzEw%252FAc3MjD8BmpmZPwEK1yM8AAAAAAEAopQaHQAAAAABAAAAopQaTUIBAAAAopQaTUIAAAEAAAAAAAAAAAAAAAAAAAGAJv3w318DAAABCtcjPQEAAYnPnTkA

Swaps with raydium and orca:
https://explorer.solana.com/tx/inspector?message=gAEABxaXasgwG9FmBmJ2%252FeNrIAxUsmaYpybho0QequNylSxXHBulZrrZuPCCkUPtQFrNDgnWxZA22aB6wYsY%252BhPIdXNQJceno90zON8zu%252Bl%252BewByl98uAZ%252FaEfxsasiqpRJ1LL0z8UB%252Fxest9%252BZ5F0XgExM1pHutf4FtQAsRGtRTxaAcOjqIkUXxYGvRa5n61CShDFBxDWbCtYJwF5uoWEwWerlWVoWHlauaaqRTdbR2JiIO9W7dhqPFBnu9hE1LMiUUDqlZoy8pms014AkelE4HnYAflAFeqwD0JOcfYZFJR89KM20x7Z0E7L2C%252BNtRIwFPTDi%252BO6Hb8ylP32fbsEgnB96EeFIcsXnOu4WJtVai1eyU0kmGgv35uyr1rWTkkcxBU9qjh%252B%252FtofuDGoGuQU%252Be1mtb4VJjICcu4NnpYwrvk3Gl%252F8l7Bswg2qFGunq8R1HKc9GNOTr0gDT32bXvN%252BvVkGcc09IQgxHG%252BTCZA38iRrUK0P2sydCpmwJnhjtdQrZ4evfdebrmQGNmnRr3u720pUPcedmhj4zC3qwUAzNBQvyhtuOSRQEulRQNheBv5zEdivyq6zCgtCRmChF2tTcFp9vs9Pt%252FriJ55Zt1Cmt9YjwauNy4cC1QdA1O6O%252BFrL4HWkwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMGRm%252FlIRcy%252F%252BytunLDm%252Be8jOW7xfcSayxDmzpAAAAABt324ddloZPZy%252BFGzut5rBy0he1fWzeROoz1hX7%252FAKkOA2hfjpCQU%252BRYEhxm9adq7cdwaqEcgviqlSqPK3h5qYALjxPNY%252BSu32%252FMMTzirBKDNyAviIgMAl9BzONF7auhpdXKngTPXbWQtxS6L%252BMssVkTP8HBkrciV%252F0H05ywQB73hjxHYVXjra%252FGPOeXGk0fLLKjCbk%252Bmgs2w6d2oCwimAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAABQLgkwQAFAoAFQoLDQUEBhEMKfjGnpHhdYfIAGXNHQAAAABPwCYFAAAAANwsu0oNEnba%252FXBHAAAAAAABEgsRAAkNDgsHAgEDEyr4xp6R4XWHyE%252FAJgUAAAAAV4nSHQAAAABQOwEAAQAAAAAAAAAAAAAAAQEPAgAIDAIAAADoAwAAAAAAAAA%253D

**Comment by brittcyr** [comment]
Mango:
https://explorer-git-sim-brittcyrs-projects.vercel.app/tx/inspector?cluster=custom&customUrl=https%3A%2F%2Fmango.rpcpool.com%2F6f7b66c979597f87cca334b8228b&signatures=%255B%255D&message=AgEFCRs9oIYKLgvCL0jE6NPJcNK91pYWO260fYJcwfKrssMBSKw4Jx8oqxsS5JQ5vd9UhxCU5IMqVseo7Fe9GNNXmAARLXtRsizCsBmLuz5XxlatdGYbAf3cIO%252Fv2redwO548ahCTS0yu5ZFC9WbgBoYsqjYpBA2jBaVRU%252F8xUOqzUrGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAx2OF93g9ZwY4HW5jKnWtlyPok7VBtIGxevjwYDwI3f1sXx8hqbnOfrxdRgYNj6U%252BQi%252FNwBM5tP7zxl73S9R8cnpF790xBuhB8qzeCi8CgG%252BhgNtFM%252FFwCEvgNQ7k1lS8DBkZv5SEXMv%252Fsrbpyw5vnvIzlu8X3EmssQ5s6QAAAAKniOeM8HNrJQualz8ir6fopKgIS9LznmB%252Bq%252BDvmdglOAggABQJAQg8ABQYGAQMHBAKhAZHMC9Guhk8%252BAcD3509w6CJfaPPr8MaPrubzIS6rA0AhgdwhdwHUfLHXAc3MzD0B%252BgAAAAEAAAHNzMw9AW8SgzoBZmZmPwHNzEw%252FAc3MjD8BmpmZPwEK1yM8AAAAAAEAopQaHQAAAAABAAAAopQaTUIBAAAAopQaTUIAAAEAAAAAAAAAAAAAAAAAAAGAJv3w318DAAABCtcjPQEAAYnPnTkA
Screen Shot 2024-06-20 at 2 12 19 PM


Swaps:
https://explorer-git-sim-brittcyrs-projects.vercel.app/tx/inspector?cluster=custom&customUrl=https%3A%2F%2Fmango.rpcpool.com%2F6f7b66c979597f87cca334b8228b&signatures=%255B%255D&message=gAEABxaXasgwG9FmBmJ2%252FeNrIAxUsmaYpybho0QequNylSxXHBulZrrZuPCCkUPtQFrNDgnWxZA22aB6wYsY%252BhPIdXNQJceno90zON8zu%252Bl%252BewByl98uAZ%252FaEfxsasiqpRJ1LL0z8UB%252Fxest9%252BZ5F0XgExM1pHutf4FtQAsRGtRTxaAcOjqIkUXxYGvRa5n61CShDFBxDWbCtYJwF5uoWEwWerlWVoWHlauaaqRTdbR2JiIO9W7dhqPFBnu9hE1LMiUUDqlZoy8pms014AkelE4HnYAflAFeqwD0JOcfYZFJR89KM20x7Z0E7L2C%252BNtRIwFPTDi%252BO6Hb8ylP32fbsEgnB96EeFIcsXnOu4WJtVai1eyU0kmGgv35uyr1rWTkkcxBU9qjh%252B%252FtofuDGoGuQU%252Be1mtb4VJjICcu4NnpYwrvk3Gl%252F8l7Bswg2qFGunq8R1HKc9GNOTr0gDT32bXvN%252BvVkGcc09IQgxHG%252BTCZA38iRrUK0P2sydCpmwJnhjtdQrZ4evfdebrmQGNmnRr3u720pUPcedmhj4zC3qwUAzNBQvyhtuOSRQEulRQNheBv5zEdivyq6zCgtCRmChF2tTcFp9vs9Pt%252FriJ55Zt1Cmt9YjwauNy4cC1QdA1O6O%252BFrL4HWkwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMGRm%252FlIRcy%252F%252BytunLDm%252Be8jOW7xfcSayxDmzpAAAAABt324ddloZPZy%252BFGzut5rBy0he1fWzeROoz1hX7%252FAKkOA2hfjpCQU%252BRYEhxm9adq7cdwaqEcgviqlSqPK3h5qYALjxPNY%252BSu32%252FMMTzirBKDNyAviIgMAl9BzONF7auhpdXKngTPXbWQtxS6L%252BMssVkTP8HBkrciV%252F0H05ywQB73hjxHYVXjra%252FGPOeXGk0fLLKjCbk%252Bmgs2w6d2oCwimAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAABQLgkwQAFAoAFQoLDQUEBhEMKfjGnpHhdYfIAGXNHQAAAABPwCYFAAAAANwsu0oNEnba%252FXBHAAAAAAABEgsRAAkNDgsHAgEDEyr4xp6R4XWHyE%252FAJgUAAAAAV4nSHQAAAABQOwEAAQAAAAAAAAAAAAAAAQEPAgAIDAIAAADoAwAAAAAAAAA%253D
Screen Shot 2024-06-20 at 2 12 57 PM

**Comment by brittcyr** [comment]
@ngundotra need more examples?

**Comment by ngundotra** [comment]
@brittcyr will take this back up tomorrow. thanks for your patience 🙏

**Comment by ngundotra** [comment]
@brittcyr Looks great! Merging. Thanks

**Review by ngundotra — APPROVED** [review]

**Pull request merged**
