### PR TITLE
The inspector will now accept a transaction, a versioned transaction, a message, or a versioned message

### PR DESCRIPTION
**Pull request by steveluscher**
# Test plan

Visit `/tx/inspector` and paste in the following.

## A legacy transaction

```
AgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEDBr+lhud1kh3/T9hG50HSqUZkigC5oGEhBnZyS4LPpMtOoYNBYtiONrVgr6gFD9j0si5UpgcznwgouB+gSvl3B6SV8XEiQm+zr1FpjDDa95qgzbREkjpJrSxl/GrpAnuA0gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqHYF5E3VCqYNDe9/ip6slV/U1yKeHIraKSdwAAAAAAGp9UXGSxcUSGMyUw9SvF/WNruCJuh/UTj29mKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgMDAAIBYwMAAAChg0Fi2I42tWCvqAUP2PSyLlSmBzOfCCi4H6BK+XcHpAcAAAAAAAAAc3Rha2U6MADKmjsAAAAAyAAAAAAAAAAGodgXkTdUKpg0N73+KnqyVX9TXIp4citopJ3AAAAAAAQCAgV0AAAAAL+lhud1kh3/T9hG50HSqUZkigC5oGEhBnZyS4LPpMtOv6WG53WSHf9P2EbnQdKpRmSKALmgYSEGdnJLgs+ky04AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
```

# A version 0 transaction

```
AgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBgAIBAwa/pYbndZId/0/YRudB0qlGZIoAuaBhIQZ2ckuCz6TLTqGDQWLYjja1YK+oBQ/Y9LIuVKYHM58IKLgfoEr5dweklfFxIkJvs69RaYww2veaoM20RJI6Sa0sZfxq6QJ7gNIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAah2BeRN1QqmDQ3vf4qerJVf1NcinhyK2ikncAAAAAABqfVFxksXFEhjMlMPUrxf1ja7gibof1E49vZigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDAwACAWMDAAAAoYNBYtiONrVgr6gFD9j0si5UpgcznwgouB+gSvl3B6QHAAAAAAAAAHN0YWtlOjAAypo7AAAAAMgAAAAAAAAABqHYF5E3VCqYNDe9/ip6slV/U1yKeHIraKSdwAAAAAAEAgIFdAAAAAC/pYbndZId/0/YRudB0qlGZIoAuaBhIQZ2ckuCz6TLTr+lhud1kh3/T9hG50HSqUZkigC5oGEhBnZyS4LPpMtOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

# A legacy message

```
AgEDBr+lhud1kh3/T9hG50HSqUZkigC5oGEhBnZyS4LPpMtOoYNBYtiONrVgr6gFD9j0si5UpgcznwgouB+gSvl3B6SV8XEiQm+zr1FpjDDa95qgzbREkjpJrSxl/GrpAnuA0gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqHYF5E3VCqYNDe9/ip6slV/U1yKeHIraKSdwAAAAAAGp9UXGSxcUSGMyUw9SvF/WNruCJuh/UTj29mKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgMDAAIBYwMAAAChg0Fi2I42tWCvqAUP2PSyLlSmBzOfCCi4H6BK+XcHpAcAAAAAAAAAc3Rha2U6MADKmjsAAAAAyAAAAAAAAAAGodgXkTdUKpg0N73+KnqyVX9TXIp4citopJ3AAAAAAAQCAgV0AAAAAL+lhud1kh3/T9hG50HSqUZkigC5oGEhBnZyS4LPpMtOv6WG53WSHf9P2EbnQdKpRmSKALmgYSEGdnJLgs+ky04AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
```

# A versioned message

```
gAIBAwa/pYbndZId/0/YRudB0qlGZIoAuaBhIQZ2ckuCz6TLTqGDQWLYjja1YK+oBQ/Y9LIuVKYHM58IKLgfoEr5dweklfFxIkJvs69RaYww2veaoM20RJI6Sa0sZfxq6QJ7gNIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAah2BeRN1QqmDQ3vf4qerJVf1NcinhyK2ikncAAAAAABqfVFxksXFEhjMlMPUrxf1ja7gibof1E49vZigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDAwACAWMDAAAAoYNBYtiONrVgr6gFD9j0si5UpgcznwgouB+gSvl3B6QHAAAAAAAAAHN0YWtlOjAAypo7AAAAAMgAAAAAAAAABqHYF5E3VCqYNDe9/ip6slV/U1yKeHIraKSdwAAAAAAEAgIFdAAAAAC/pYbndZId/0/YRudB0qlGZIoAuaBhIQZ2ckuCz6TLTr+lhud1kh3/T9hG50HSqUZkigC5oGEhBnZyS4LPpMtOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

### CODE REVIEW

**Comment by steveluscher** [comment]
I got tired of Explorer not working with the output of `--dump-transaction-message`.

**Comment by ngundotra** [comment]
Can you update the inspector's here with the supported byte data?

Screenshot 2024-05-17 at 5 09 08 PM

**Comment by steveluscher** [comment]
> Can you update the inspector's text here with the supported byte data?

I'm so afraid to, because that would mean committing to keeping that working forever, when really I have half a mind that we should just eliminate support for decoding wire transactions altogether.

**Comment by steveluscher** [comment]
To be clear, pasting a valid base64 legacy message into Explorer today will break it. Try the ‘legacy message’ with Explorer in prod right now.

**Comment by steveluscher** [comment]
ie. This is not a ‘feature’ PR, it's a bug fix.

**Comment by ngundotra** [comment]
What do you think about adding the following somewhere in the UI?

`support for tx.serialize() will end soon, please transition to tx.message.serialize()`
or 
`supported formats Message, VersionedMessage, and (deprecated) Transaction, (deprecated) VersionedTransaction`

**Comment by steveluscher** [comment]
> What do you think about adding the following somewhere in the UI?

I think that would be a fine thing for someone else to do, who's actually going to see that through (ie. not me).

**Pull request merged**
