### PR TITLE
adding KIN to the token registry

### PR DESCRIPTION
**Pull request by Blahartinger**

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
@oJshua , I think this needs to be in the monorepo, doesn't it?

**Comment by mvines** [comment]
Ack, yes.  We'll need to rewrite the history in this repo to remove that commit or future exports from the monorepo into this mirror will fail

**Comment by oJshua** [comment]
Ah, yes. I can rewrite the history.

**Comment by oJshua** [comment]
Thanks guys. @mvines @CriesofCarrots, Rewrote the history.

**Pull request merged**
